package al.tetra.licence.controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.security.NoSuchAlgorithmException;
import java.util.ResourceBundle;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import al.tetra.licence.entity.Certificate;
import al.tetra.licence.entity.Perdorues;
import al.tetra.licence.service.CertificateService;
import al.tetra.licence.service.LicenceService;
import al.tetra.licence.service.PerdoruesService;
import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;

import javafx.scene.control.Label;

import javafx.scene.control.PasswordField;
import javafx.scene.control.RadioButton;
import javafx.scene.input.MouseEvent;

import javafx.scene.control.Menu;
import javafx.scene.control.MenuBar;
import javafx.scene.control.MenuButton;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import net.rgielen.fxweaver.core.FxmlView;

@Component
@FxmlView("/fxml/mainFxml.fxml")
public class mainController implements Initializable {

	@Autowired
	private LicenceService licenceService;
	@Autowired
	private PerdoruesService perdoruesService;

	@FXML
	private MenuBar menuShtoKarteleTeRe;
	@FXML
	private Menu fileMenu;
	@FXML
	private MenuItem mbyllMenuItem1;
	@FXML
	private Menu pacientMenu;
	@FXML
	private MenuItem regjistroPacientMenuItem1;
	@FXML
	private MenuItem shikoKarteleMenuItem2;
	@FXML
	private MenuItem shtoKarteleTeReMenuItem3;
	@FXML
	private Menu receteMenu;
	@FXML
	private MenuItem leshoReceteMenuItem1;
	@FXML
	private Menu ilacMenu;
	@FXML
	private MenuItem perditesoIlacMenuItem1;
	@FXML
	private MenuItem shitIlacMenuItem2;
	@FXML
	private Menu sherbimeMenu;
	@FXML
	private MenuItem editoPerdoruesMenuItem1;
	@FXML
	private MenuItem shtoPerdoruesMenuItem2;
	@FXML
	private MenuButton adminMenuButton;
	@FXML
	private MenuItem mbyllMenuItem;
	@FXML
	private MenuItem quit;
	@FXML
	private Label generateLicenceKeyTab;
	@FXML
	private Label validateCertificateTab;
	@FXML
	private Label generateCertificateTab;
	@FXML
	private Label modifikoPerdoruesLabel;
	@FXML
	private Pane container;
	@FXML
	private Pane editPerdoruesPane;
	@FXML
	private Pane leshoRecetePane1;
	@FXML
	private Pane perditesoIlacePane;
	@FXML
	private Pane shikoKartelePane1;
	@FXML
	private Pane shitIlacePane;
	@FXML
	private Pane shtoKarteleTeRePane;
	@FXML
	private Pane shtoPacient;
	@FXML
	private Pane adminPane;
	@FXML
	private Pane generateCertificatePane;
	@FXML
	private Pane generateLicencePane;
	@FXML
	private Pane generatePasswordPane;
	@FXML
	private Pane modifikoPerdoruesPane;
	@FXML
	private Label firstNameLabel;
	@FXML
	private TextField emerTextField;
	@FXML
	private Label lastNameLabel;
	@FXML
	private TextField mbiemerTextField;
	@FXML
	private Label mobileLabel;
	@FXML
	private TextField telefonTextField;
	@FXML
	private Label emailLabel;
	@FXML
	private TextField emailTextField;
	@FXML
	private Label addressLabel;
	@FXML
	private TextField addressTextField;
	@FXML
	private Label genderLabel;
	@FXML
	private RadioButton gjiniaMashkullRadioButton;
	@FXML
	private RadioButton gjiniaFemerRadioButton;
	@FXML
	private Label usernameLabel;
	@FXML
	private TextField usernameTextField;
	@FXML
	private Label paswwordLabel;
	@FXML
	private PasswordField passwordField;
	@FXML
	private Label confirmPaswwordLabel;
	@FXML
	private Label messageLabel;
	@FXML
	private PasswordField confirmPasswordTextField;
	@FXML
	private TextField roliTextField;
	@FXML
	private Button registerButton;
	@FXML
	private ImageView imageAdmin;

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		File file = new File("/images/doctor-clinic.jpg");
		Image image = new Image(file.getPath(), 200, 160, false, true);
		imageAdmin.setImage(image);

	}

	// Event Listener on MenuItem[#quit].onAction
	@FXML
	public void quitApp(ActionEvent event) {
		// TODO Autogenerated
		System.exit(0);
	}

	// Event Listener on Label[#generateLicenceKeyTab].onMouseClicked
	@FXML
	public void openEditPerdoruesPane(ActionEvent event) {
		// TODO Autogenerated
		
		leshoRecetePane1.setVisible(false);
		perditesoIlacePane.setVisible(false);
		shikoKartelePane1.setVisible(false);
		shitIlacePane.setVisible(false);
		shtoKarteleTeRePane.setVisible(false);
		shtoPacient.setVisible(false);
		adminPane.setVisible(false);
		editPerdoruesPane.setVisible(true);
	}

	@FXML
	public void openShtoPacient(ActionEvent event) {
		
		shitIlacePane.setVisible(false);
		editPerdoruesPane.setVisible(false);
		leshoRecetePane1.setVisible(false);
		shtoKarteleTeRePane.setVisible(false);
		shikoKartelePane1.setVisible(false);
		adminPane.setVisible(false);
		shtoPacient.setVisible(true);
		
	}

	@FXML
	public void openShtoKarteleTeRe(ActionEvent event) {
		editPerdoruesPane.setVisible(false);
		shtoPacient.setVisible(false);
		shitIlacePane.setVisible(false);
		shikoKartelePane1.setVisible(false);
		leshoRecetePane1.setVisible(false);
		adminPane.setVisible(false);
		shtoKarteleTeRePane.setVisible(true);
		
	}

	@FXML
	public void openShitIlace(ActionEvent event) {
		editPerdoruesPane.setVisible(false);
		shitIlacePane.setVisible(true);
		shtoPacient.setVisible(false);
		leshoRecetePane1.setVisible(false);
		adminPane.setVisible(false);
		shtoKarteleTeRePane.setVisible(false);
	}

	@FXML
	public void openPerditesoIlac(ActionEvent event) {
		shitIlacePane.setVisible(false);
		editPerdoruesPane.setVisible(false);
		shtoPacient.setVisible(false);
		shtoKarteleTeRePane.setVisible(false);
		shikoKartelePane1.setVisible(false);
		leshoRecetePane1.setVisible(false);
		adminPane.setVisible(false);
		perditesoIlacePane.setVisible(true);
	}
	@FXML
	public void openShikoKartele(ActionEvent event) {
		shitIlacePane.setVisible(false);
		editPerdoruesPane.setVisible(false);
		shtoPacient.setVisible(false);
		shtoKarteleTeRePane.setVisible(false);
		perditesoIlacePane.setVisible(false);
		leshoRecetePane1.setVisible(false);
		adminPane.setVisible(false);
		shikoKartelePane1.setVisible(true);
		
	}
	@FXML
	public void openLeshoRecete(ActionEvent event) {
		shitIlacePane.setVisible(false);
		editPerdoruesPane.setVisible(false);
		shtoPacient.setVisible(false);
		shtoKarteleTeRePane.setVisible(false);
		perditesoIlacePane.setVisible(false);
		shikoKartelePane1.setVisible(false);
		adminPane.setVisible(false);
		leshoRecetePane1.setVisible(true);
	}
	@FXML
	public void openShtoPerdorues(ActionEvent event) {
		shitIlacePane.setVisible(false);
		editPerdoruesPane.setVisible(false);
		shtoPacient.setVisible(false);
		shtoKarteleTeRePane.setVisible(false);
		perditesoIlacePane.setVisible(false);
		shikoKartelePane1.setVisible(false);
		leshoRecetePane1.setVisible(false);
		adminPane.setVisible(true);
	}

	@FXML
	public void shtoPerdorues(ActionEvent event) {
		RadioButton selected = null;
		if (gjiniaFemerRadioButton.isSelected()) {
			selected = gjiniaFemerRadioButton;
		} else {
			selected = gjiniaMashkullRadioButton;
		}
		Perdorues p = perdoruesService.shtoPerdoruesTeRi(emerTextField.getText(), mbiemerTextField.getText(),
				roliTextField.getText(), telefonTextField.getText(), emailTextField.getText(),
				addressTextField.getText(), selected.getText(), usernameTextField.getText(), passwordField.getText(),
				confirmPasswordTextField.getText(), messageLabel);
		if (p != null) {
			messageLabel.setText("Useri u krijua me sukses");
			registerButton.setDisable(true);
		}

	}

}
